shizlib.Crafting = shizlib.Crafting or {}

local CheckBrench = function(self, ply, brench)
    local pos = ply:GetPos()
    local flag = false
    local benchEnt = nil
    
    for _, e in pairs(ents.FindInSphere(pos, CFG and CFG.useDist or 150)) do
        if IsValid(e) and e:GetClass() == brench then
            flag = true
            benchEnt = e
            break
        end
    end
    
    if flag then
        return true, benchEnt
    else
        return false, nil
    end
end

shizlib.Crafting.CFG = shizlib.Crafting.CFG or {}
shizlib.Crafting.Recipes = {
    {
        name = "Glock 17",
        description = "Нелегально собранный пистолет из композитных материалов. Легко спрятать под курткой.",
        amount = 1,
        craftTime = 60,
        resources = {
            { class = "screws", amount = 7 },
            { class = "spring", amount = 2 },
            { class = "aluminum", amount = 4 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_glock17",
        icon = "pistolet",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Glock 26",
        description = "Нелегально собранный пистолет из композитных материалов. Легко спрятать под курткой.",
        amount = 1,
        craftTime = 60,
        resources = {
            { class = "screws", amount = 7 },
            { class = "spring", amount = 2 },
            { class = "aluminum", amount = 4 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_glock26",
        icon = "pistolet",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "FNX-45",
        description = "Усиленная версия с цельнометаллической рамой. Выдерживает жесткие нагрузки и перепады температур, но ощутимо тяжелее в кармане.",
        amount = 1,
        craftTime = 60,
        resources = {
            { class = "screws", amount = 11 },
            { class = "spring", amount = 2 },
            { class = "steel", amount = 4 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_fn45",
        icon = "pistolet",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "ČZ 75",
        description = "Восточноевропейская классика с цельнометаллической рамой. Ценится за неприхотливость и возможность быстрой разборки без специального инструмента.",
        amount = 1,
        craftTime = 60,
        resources = {
            { class = "screws", amount = 9 },
            { class = "spring", amount = 2 },
            { class = "steel", amount = 6 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_cz75",
        icon = "pistolet",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Colt M1911",
        description = "Классика, проверенная временем. Убойный калибр и тяжелый металлический корпус, восстановленный в кустарных условиях.",
        amount = 1,
        craftTime = 65,
        resources = {
            { class = "screws", amount = 11 },
            { class = "spring", amount = 4 },
            { class = "steel", amount = 6 },
            { class = "wood", amount = 2 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_m1911",
        icon = "pistolet",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Colt M45A1",
        description = "Модернизированная версия классики. Часто используется наемниками благодаря балансу между пробивной силой и надежностью.",
        amount = 1,
        craftTime = 70,
        resources = {
            { class = "screws", amount = 9 },
            { class = "spring", amount = 4 },
            { class = "steel", amount = 7 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "tools", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_m45",
        icon = "pistolet",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Beretta M9",
        description = "Табельное оружие, чертежи которого утекли на черный рынок. Хорошая точность и вместительный магазин.",
        amount = 1,
        craftTime = 65,
        resources = {
            { class = "screws", amount = 7 },
            { class = "spring", amount = 2 },
            { class = "aluminum", amount = 6 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_m9beretta",
        icon = "pistolet",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Beretta PX4",
        description = "Сложный в производстве пистолет с вращающимся стволом. Дорогие сплавы окупаются отличной эргономикой.",
        amount = 1,
        craftTime = 70,
        resources = {
            { class = "screws", amount = 11 },
            { class = "spring", amount = 4 },
            { class = "aluminum", amount = 7 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_px4beretta",
        icon = "pistolet",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Walther P22",
        description = "Дешевая пукалка из подручных труб и металла. Часто заклинивает, но для самообороны в подворотне сгодится.",
        amount = 1,
        craftTime = 50,
        resources = {
            { class = "screws", amount = 6 },
            { class = "spring", amount = 2 },
            { class = "steel", amount = 2 },
            { class = "pipe", amount = 2 },
            { class = "rifle_body", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_p22",
        icon = "pistolet",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "HK USP",
        description = "Дешевая пукалка из подручных труб и металла. Часто заклинивает, но для самообороны в подворотне сгодится.",
        amount = 1,
        craftTime = 70,
        resources = {
            { class = "screws", amount = 11 },
            { class = "spring", amount = 4 },
            { class = "aluminum", amount = 7 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_hk_usp",
        icon = "pistolet",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "TEC-9",
        description = "Импровизированный автоматический пистолет из штампованной стали. Дает шквальный огонь на близкой дистанции, но требует постоянного контроля перегрева.",
        amount = 1,
        craftTime = 60,
        resources = {
            { class = "screws", amount = 9 },
            { class = "spring", amount = 2 },
            { class = "steel", amount = 6 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_tec9",
        icon = "pistolet",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Desert Eagle",
        description = "Статусная «пушка» криминальных авторитетов. Пробивает легкие бронежилеты и оставляет огромные дыры, но требует ювелирной сборки.",
        amount = 1,
        craftTime = 100,
        resources = {
            { class = "screws", amount = 14 },
            { class = "spring", amount = 4 },
            { class = "steel", amount = 11 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "tools", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_deagle",
        icon = "pistolet",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Colt King Cobra",
        description = "Самодельный револьвер под магнумовский патрон. Никакой сложной автоматики — только грубая сила и оглушительный грохот.",
        amount = 1,
        craftTime = 80,
        resources = {
            { class = "screws", amount = 11 },
            { class = "spring", amount = 2 },
            { class = "steel", amount = 9 },
            { class = "pipe", amount = 4 },
            { class = "wood", amount = 2 },
        },
        base = "weapon",
        entity = "weapon_revolver357",
        icon = "revolver",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Manurhin MR-96",
        description = "Самодельный револьвер под магнумовский патрон. Никакой сложной автоматики — только грубая сила и оглушительный грохот.",
        amount = 1,
        craftTime = 80,
        resources = {
            { class = "screws", amount = 11 },
            { class = "spring", amount = 2 },
            { class = "steel", amount = 9 },
            { class = "pipe", amount = 4 },
            { class = "wood", amount = 2 },
        },
        base = "weapon",
        entity = "weapon_revolver2",
        icon = "revolver",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "AR Pistol",
        description = "Укороченная штурмовая винтовка без приклада. Любимое оружие уличных банд для стычек в тесных помещениях.",
        amount = 1,
        craftTime = 130,
        resources = {
            { class = "screws", amount = 18 },
            { class = "spring", amount = 6 },
            { class = "aluminum", amount = 7 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "rifle_clip", amount = 1 },
            { class = "tools", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_ar_pistol",
        icon = "assault_rifle",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Draco",
        description = "Обрезок Калашникова, собранный в гараже. Отвратительная точность компенсируется сумасшедшей плотностью огня.",
        amount = 1,
        craftTime = 150,
        resources = {
            { class = "screws", amount = 21 },
            { class = "spring", amount = 4 },
            { class = "steel", amount = 11 },
            { class = "wood", amount = 6 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "rifle_clip", amount = 1 },
            { class = "tools", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_draco",
        icon = "assault_rifle",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Remington 870",
        description = "Помповый дробовик, собранный из гражданских запчастей. Идеальный аргумент при незваных гостях на пороге.",
        amount = 1,
        craftTime = 110,
        resources = {
            { class = "screws", amount = 11 },
            { class = "spring", amount = 4 },
            { class = "steel", amount = 7 },
            { class = "wood", amount = 4 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_butt", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_remington870",
        icon = "shotgun",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Mossber 590A1",
        description = "Тяжелый тактический дробовик. Выдерживает суровые условия эксплуатации и не подведет во время затяжного боя.",
        amount = 1,
        craftTime = 120,
        resources = {
            { class = "screws", amount = 14 },
            { class = "spring", amount = 4 },
            { class = "steel", amount = 9 },
            { class = "aluminum", amount = 4 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "rifle_butt", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_m590a1",
        icon = "shotgun",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Benelli M4",
        description = "Тяжелый тактический дробовик. Выдерживает суровые условия эксплуатации и не подведет во время затяжного боя.",
        amount = 1,
        craftTime = 120,
        resources = {
            { class = "screws", amount = 14 },
            { class = "spring", amount = 4 },
            { class = "steel", amount = 9 },
            { class = "aluminum", amount = 4 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "rifle_butt", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_xm1014",
        icon = "shotgun",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "TOZ-106",
        description = "Тяжелый тактический дробовик. Выдерживает суровые условия эксплуатации и не подведет во время затяжного боя.",
        amount = 1,
        craftTime = 100,
        resources = {
            { class = "screws", amount = 12 },
            { class = "spring", amount = 3 },
            { class = "steel", amount = 6 },
            { class = "aluminum", amount = 3 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "rifle_butt", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_toz106",
        icon = "shotgun",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "IZh-43",
        description = "Дедовская двустволка. Собрана из водопроводных труб и куска дерева. Проста как дубина, бьет так же больно.",
        amount = 1,
        craftTime = 80,
        resources = {
            { class = "screws", amount = 7 },
            { class = "spring", amount = 4 },
            { class = "steel", amount = 4 },
            { class = "wood", amount = 7 },
            { class = "pipe", amount = 4 },
            { class = "rifle_butt", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_doublebarrel",
        icon = "shotgun",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Sawed-off IZh-43",
        description = "Дедовская двустволка. Собрана из водопроводных труб и куска дерева. Проста как дубина, бьет так же больно.",
        amount = 1,
        craftTime = 80,
        resources = {
            { class = "screws", amount = 7 },
            { class = "spring", amount = 4 },
            { class = "steel", amount = 2 },
            { class = "wood", amount = 4 },
            { class = "pipe", amount = 4 },
            { class = "rifle_butt", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_doublebarrel_short",
        icon = "shotgun",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "VPO-209",
        description = "Охотничий гладкоствольный карабин, переделанный умельцами под боевой аналог. Дешево, сердито и безотказно.",
        amount = 1,
        craftTime = 160,
        resources = {
            { class = "screws", amount = 21 },
            { class = "spring", amount = 6 },
            { class = "steel", amount = 14 },
            { class = "wood", amount = 6 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "rifle_butt", amount = 1 },
            { class = "rifle_clip", amount = 1 },
            { class = "tools", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_vpo209",
        icon = "assault_rifle",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "AR-15",
        description = "Кастомная полуавтоматическая винтовка из качественных сплавов. Требует аккуратной сборки и дорогих инструментов, но результат того стоит.",
        amount = 1,
        craftTime = 190,
        resources = {
            { class = "screws", amount = 28 },
            { class = "spring", amount = 6 },
            { class = "steel", amount = 11 },
            { class = "aluminum", amount = 11 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "rifle_butt", amount = 1 },
            { class = "rifle_clip", amount = 1 },
            { class = "tools", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_ar15",
        icon = "assault_rifle",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Mini-14",
        description = "Кастомная полуавтоматическая винтовка из качественных сплавов. Требует аккуратной сборки и дорогих инструментов, но результат того стоит.",
        amount = 1,
        craftTime = 190,
        resources = {
            { class = "screws", amount = 21 },
            { class = "spring", amount = 6 },
            { class = "steel", amount = 14 },
            { class = "wood", amount = 6 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "rifle_butt", amount = 1 },
            { class = "rifle_clip", amount = 1 },
            { class = "tools", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_mini14",
        icon = "assault_rifle",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Karabiner 98k",
        description = "Кастомная полуавтоматическая винтовка из качественных сплавов. Требует аккуратной сборки и дорогих инструментов, но результат того стоит.",
        amount = 1,
        craftTime = 190,
        resources = {
            { class = "screws", amount = 28 },
            { class = "spring", amount = 6 },
            { class = "steel", amount = 11 },
            { class = "wood", amount = 6 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "rifle_butt", amount = 1 },
            { class = "tools", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_kar98",
        icon = "sniper_rifle",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "SKS",
        description = "Кастомная полуавтоматическая винтовка из качественных сплавов. Требует аккуратной сборки и дорогих инструментов, но результат того стоит.",
        amount = 1,
        craftTime = 190,
        resources = {
            { class = "screws", amount = 28 },
            { class = "spring", amount = 6 },
            { class = "steel", amount = 11 },
            { class = "wood", amount = 11 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "rifle_butt", amount = 1 },
            { class = "rifle_clip", amount = 1 },
            { class = "tools", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_sks",
        icon = "sniper_rifle",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    -- ==========================================
    -- НОВЫЕ АВТОМАТИЧЕСКИЕ ОРУЖИЯ
    -- ==========================================
    {
        name = "M16A2",
        description = "Классическая штурмовая винтовка США с режимом отсечки по 3 выстрела. Высокая дальность стрельбы и точность.",
        amount = 1,
        craftTime = 220,
        resources = {
            { class = "screws", amount = 30 },
            { class = "spring", amount = 8 },
            { class = "steel", amount = 15 },
            { class = "aluminum", amount = 15 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "rifle_butt", amount = 1 },
            { class = "rifle_clip", amount = 1 },
            { class = "tools", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_m16a2",
        icon = "assault_rifle",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "MP5",
        description = "Легендарный пистолет-пулемет, используемый спецподразделениями по всему миру. Крайне сбалансирован и надежен.",
        amount = 1,
        craftTime = 160,
        resources = {
            { class = "screws", amount = 22 },
            { class = "spring", amount = 6 },
            { class = "steel", amount = 12 },
            { class = "aluminum", amount = 8 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "rifle_butt", amount = 1 },
            { class = "rifle_clip", amount = 1 },
            { class = "tools", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_mp5",
        icon = "assault_rifle",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "MP7",
        description = "Современный компактный пистолет-пулемет. Отличается высокой скорострельностью и превосходным бронепробитием.",
        amount = 1,
        craftTime = 180,
        resources = {
            { class = "screws", amount = 24 },
            { class = "spring", amount = 6 },
            { class = "steel", amount = 8 },
            { class = "aluminum", amount = 14 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "rifle_clip", amount = 1 },
            { class = "tools", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_mp7",
        icon = "assault_rifle",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Skorpion",
        description = "Компактный чехословацкий пистолет-пулемет. Легкий, скорострельный, незаменим в ближнем бою.",
        amount = 1,
        craftTime = 120,
        resources = {
            { class = "screws", amount = 16 },
            { class = "spring", amount = 4 },
            { class = "steel", amount = 10 },
            { class = "aluminum", amount = 4 },
            { class = "rifle_barrel", amount = 1 },
            { class = "rifle_body", amount = 1 },
            { class = "rifle_clip", amount = 1 },
        },
        base = "weapon",
        entity = "weapon_skorpion",
        icon = "pistolet",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    -- ==========================================
    -- РЕСУРСЫ ДЛЯ КРАФТА
    -- ==========================================
    {
        name = "Ствол",
        description = "Оружейный ствол с нанесенными вручную нарезами. Способен выдержать высокое давление пороховых газов.",
        amount = 1,
        craftTime = 45,
        resources = {
            { class = "steel", amount = 8 },
            { class = "pipe", amount = 2 },
            { class = "screws", amount = 4 },
        },
        base = "resource",
        entity = "rifle_barrel",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Корпус",
        description = "Ствольная коробка со спусковым механизмом. Сердце любого качественного огнестрельного оружия.",
        amount = 1,
        craftTime = 55,
        resources = {
            { class = "steel", amount = 10 },
            { class = "aluminum", amount = 4 },
            { class = "screws", amount = 12 },
        },
        base = "resource",
        entity = "rifle_body",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Приклад",
        description = "Удобный деревянно-металлический приклад. Гасит отдачу и позволяет вести комфортную прицельную стрельбу.",
        amount = 1,
        craftTime = 30,
        resources = {
            { class = "wood", amount = 10 },
            { class = "steel", amount = 4 },
            { class = "screws", amount = 8 },
        },
        base = "resource",
        entity = "rifle_butt",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Магазин",
        description = "Пружинный коробчатый магазин. Изготавливается из прочной жести и упругой стальной проволоки.",
        amount = 1,
        craftTime = 25,
        resources = {
            { class = "steel", amount = 4 },
            { class = "aluminum", amount = 2 },
            { class = "spring", amount = 4 },
        },
        base = "resource",
        entity = "rifle_clip",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Медные провода",
        description = "Толстая скрутка медных жил в плотной изоляции. Является основой для создания любой электроники.",
        amount = 2,
        craftTime = 15,
        resources = {
            { class = "copper", amount = 2 },
            { class = "tape", amount = 1 },
        },
        base = "resource",
        entity = "wire",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Электросхема",
        description = "Сложная печатная плата. Требует предельной внимательности и ювелирной точности при спайке контактов.",
        amount = 1,
        craftTime = 40,
        resources = {
            { class = "copper", amount = 3 },
            { class = "wire", amount = 4 },
            { class = "glass", amount = 1 },
            { class = "screws", amount = 2 },
        },
        base = "resource",
        entity = "motherboard",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Процессор",
        description = "Вычислительный кристалл, собранный из редких деталей. Незаменим в высокотехнологичных и умных устройствах.",
        amount = 1,
        craftTime = 60,
        resources = {
            { class = "gold", amount = 2 },
            { class = "copper", amount = 2 },
            { class = "motherboard", amount = 1 },
            { class = "glass", amount = 1 },
        },
        base = "resource",
        entity = "cpu",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Улучшенный Аккумулятор",
        description = "Сборка из обычных химических батарей, модифицированная для выдачи стабильного высокого напряжения.",
        amount = 1,
        craftTime = 45,
        resources = {
            { class = "battery", amount = 1 },
            { class = "wire", amount = 3 },
            { class = "tape", amount = 2 },
            { class = "lead", amount = 2 },
        },
        base = "resource",
        entity = "battery_c",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Порох",
        description = "Самодельная взрывчатая смесь. Смертельно опасный, но жизненно необходимый компонент для кустарного снаряжения патронов.",
        amount = 3,
        craftTime = 20,
        resources = {
            { class = "coal", amount = 3 },
            { class = "stone", amount = 1 },
        },
        base = "resource",
        entity = "gunpowder",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Инструменты",
        description = "Универсальный набор инструментов. Отвертки, напильники, пассатижи и ключи, необходимые для сборки сложного оборудования.",
        amount = 1,
        craftTime = 30,
        resources = {
            { class = "iron", amount = 4 },
            { class = "steel", amount = 2 },
            { class = "wood", amount = 2 },
        },
        base = "resource",
        entity = "tools",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Коллиматорный прицел",
        description = "Улучшает прицеливание на малой дистанции и ускоряет захват цели.",
        amount = 1,
        craftTime = 35,
        resources = {
            { class = "glass", amount = 1 },
            { class = "battery", amount = 1 },
            { class = "wire", amount = 2 },
            { class = "steel", amount = 2 },
        },
        icon = "textile",
        base = "custom",
        entity = "ent_att_holo1",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Лазерный целеуказатель",
        description = "Облегчает прицеливание на ближней дистанции и заметно ускоряет захват цели.",
        amount = 1,
        craftTime = 30,
        resources = {
            { class = "steel", amount = 3 },
            { class = "wire", amount = 2 },
            { class = "battery", amount = 1 },
            { class = "screws", amount = 2 },
        },
        icon = "textile",
        base = "custom",
        entity = "ent_att_laser2",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Подствольный фонарь",
        description = "Светодиодный фонарь для темных коридоров. Позволяет увидеть цель в кромешной темноте.",
        amount = 1,
        craftTime = 30,
        resources = {
            { class = "steel", amount = 2 },
            { class = "battery", amount = 1 },
            { class = "wire", amount = 2 },
        },
        icon = "textile",
        base = "custom",
        entity = "ent_att_laser4",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Кевларовый жилет",
        description = "Легкая броня для защиты туловища. Снижает урон и не мешает мобильности.",
        amount = 1,
        craftTime = 120,
        resources = {
            { class = "steel", amount = 8 },
            { class = "cloth", amount = 6 },
            { class = "screws", amount = 6 },
            { class = "tools", amount = 1 },
        },
        icon = "textile",
        base = "custom",
        entity = "ent_armor_vest4",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Тактический шлем",
        description = "Защищает голову от осколков и легких попаданий.",
        amount = 1,
        craftTime = 90,
        resources = {
            { class = "steel", amount = 6 },
            { class = "cloth", amount = 2 },
            { class = "screws", amount = 4 },
            { class = "tools", amount = 1 },
        },
        icon = "textile",
        base = "custom",
        entity = "ent_armor_helmet1",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Защитная маска",
        description = "Маска, защищающая лицо от мелких осколков и ударов.",
        amount = 1,
        craftTime = 80,
        resources = {
            { class = "cloth", amount = 4 },
            { class = "steel", amount = 4 },
            { class = "wire", amount = 2 },
            { class = "tools", amount = 1 },
        },
        icon = "textile",
        base = "custom",
        entity = "ent_armor_mask1",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Самодельный глушитель",
        description = "Кустарный глушитель из пластиковой бутылки и изоленты.",
        amount = 1,
        craftTime = 15,
        resources = {
            { class = "tape", amount = 2 },
            { class = "pipe", amount = 1 },
        },
        icon = "textile",
        base = "custom",
        entity = "ent_att_supressor6",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Глушитель KAC HK USP-T",
        description = "Глушитель для пистолетов. Заметно снижает звук выстрела.",
        amount = 1,
        craftTime = 40,
        resources = {
            { class = "steel", amount = 3 },
            { class = "aluminum", amount = 2 },
            { class = "screws", amount = 4 },
            { class = "tools", amount = 1 },
        },
        icon = "textile",
        base = "custom",
        entity = "ent_att_supressor3",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Глушитель Gemtech TUNDRA-SV 9mm",
        description = "Компактный глушитель пистолетного калибра 9мм.",
        amount = 1,
        craftTime = 40,
        resources = {
            { class = "steel", amount = 3 },
            { class = "aluminum", amount = 2 },
            { class = "screws", amount = 4 },
            { class = "tools", amount = 1 },
        },
        icon = "textile",
        base = "custom",
        entity = "ent_att_supressor4",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Глушитель PBS-1",
        description = "Отечественный глушитель для карабинов семейства Калашникова.",
        amount = 1,
        craftTime = 55,
        resources = {
            { class = "steel", amount = 5 },
            { class = "aluminum", amount = 3 },
            { class = "screws", amount = 6 },
            { class = "tools", amount = 1 },
        },
        icon = "textile",
        base = "custom",
        entity = "ent_att_supressor1",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Глушитель Silencerco Saker 556",
        description = "Надежный глушитель для штурмовых винтовок калибра 5.56.",
        amount = 1,
        craftTime = 55,
        resources = {
            { class = "steel", amount = 5 },
            { class = "aluminum", amount = 3 },
            { class = "screws", amount = 6 },
            { class = "tools", amount = 1 },
        },
        icon = "textile",
        base = "custom",
        entity = "ent_att_supressor2",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Глушитель Ротор 43 12К",
        description = "Массивный тактический глушитель для дробовиков 12 калибра.",
        amount = 1,
        craftTime = 65,
        resources = {
            { class = "steel", amount = 7 },
            { class = "screws", amount = 6 },
            { class = "tools", amount = 1 },
        },
        icon = "textile",
        base = "custom",
        entity = "ent_att_supressor5",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Глушитель SIG Sauer SRD762-QD",
        description = "Быстросъемный глушитель под винтовочный патрон 7.62.",
        amount = 1,
        craftTime = 70,
        resources = {
            { class = "steel", amount = 6 },
            { class = "aluminum", amount = 4 },
            { class = "screws", amount = 6 },
            { class = "tools", amount = 1 },
        },
        icon = "textile",
        base = "custom",
        entity = "ent_att_supressor7",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
    {
        name = "Глушитель SilencerCo Hybrid 46",
        description = "Универсальный глушитель, подходящий для большинства калибров.",
        amount = 1,
        craftTime = 70,
        resources = {
            { class = "steel", amount = 6 },
            { class = "aluminum", amount = 4 },
            { class = "screws", amount = 6 },
            { class = "tools", amount = 1 },
        },
        icon = "textile",
        base = "custom",
        entity = "ent_att_supressor8",
        customCheck = function(self, ply) return CheckBrench(self, ply, "shizlib_bench_workbench") end,
    },
}

for k, v in ipairs(shizlib.Crafting.Recipes) do
    v.id = k
end